@extends('layoutWithoutFormativeCenters')

@section('title') NFORMAR - Términos y condiciones @endsection
@section('og:image') @endsection
@section('description') @endsection
@section('keywords') @endsection

@section('content')
    <generic-block class="pt-lg-5 mt-lg-5 pt-2 mt-0" content="
        <h1 class='mb-5'><b>Términos y Condiciones</b></h1>
        <p class='mb-4'><b><u>Objeto.</u></b> Las presentes Condiciones Generales junto con las condiciones de Política de Privacidad y Aviso Legal, tienen como objeto regular la contratación de productos y/o servicios a través de nuestra tienda virtual ubicada en <b>https://www.nformar.com</b> del que es titular <b>ESCUELA DE HOSTELERÍA EUROPEA, S.L.</b></p>
        <p class='mb-4'><b><u>¿Como puedo acceder al curso una vez comprado?</u></b> En el mismo momento en que se realiza el pago de un curso la matricula se formaliza automáticamente. Podrás acceder a dicho curso a través del apartado <b>Mis Cursos</b> dentro de tu perfil de usuario, al hacerlo serás redirigido a nuestra plataforma de teleformación donde, por motivos de seguridad, se te pedirá que introduzcas tu usuario y tu contraseña de nuevo. Una vez dentro de la plataforma de teleformación podrás acceder a todos los contenidos del curso en formato digital.</p>
        <p class='mb-4'><b><u>¿Cuando y como recibiré mi diploma?</u></b> En el mismo momento en que completes correctamente los contenidos necesarios para ser evaluado como apto en tu curso, se generará un diploma que podrás descargar para tenerlo en formato digital, dicho documento puede ser impreso si deseas tenerlo en formato físico.</p>
        <p class='mb-4'><b><u>¿Qué formas de pago puedo usar?</u></b> Puedes encontrar más información acerca de nuestros métodos de pago aceptados en la sección <a href='{{url('paymentMethods')}}'><b>“Métodos de pago”.</b></a></p>
        <p class='mb-4'><b><u>¿Como puedo pedir una devolución?</u></b> Puedes encontrar más información acerca de nuestra política de devoluciones en la sección <a href='{{url('refunds')}}'><b>“Política de devoluciones”.</b></a></p>
        <p class='mb-4'><b><u>Capacidad de contratación.</u></b> El usuario declara bajo su responsabilidad ser mayor de edad y disponer de capacidad legal necesaria para contratar los servicios ofertados por <b>NFORMAR</b>, manifestando asimismo haber leído íntegramente las presentes condiciones generales así como en su caso, las condiciones particulares, de los productos y/o servicios ofertados objeto de contratación,entendiéndolas y aceptándolas plenamente y sin reserva alguna. Para ello, el usuario tendrá acceso en cualquier momento a las referidas condiciones e instrucciones entendiéndose vigentes las publicadas en el momento de solicitar cada producto/servicio.</p>
        <p class='mb-4'><b><u>Proceso de contratación.</u></b> Para poder iniciar el proceso de contratación es necesario que previamente se registre como usuario y cree su propia cuenta introduciendo una dirección válida de correo electrónico y rellenando los datos que se solicitan en el formulario correspondiente, necesarios para gestionar correctamente su compra. Para poder continuar el proceso, el usuario deberá aceptar la política de privacidad al pie del referido formulario. En caso de error por parte del usuario al introducir los datos solicitados, éstos podrán ser consultados y modificados en todo momento a través del apartado “Configuración”, accesible una vez que inicie sesión.</p>
        <p class='mb-4'>Una vez registrado, el usuario podrá comprar los productos/servicios seleccionados añadiéndolos a su “carrito de la compra”. Durante el proceso de compra podrá acceder a los productos seleccionados con el desglose de precios (impuestos incluidos).</p>
        <p class='mb-4'>En el apartado “Configuración” podrá añadir y modificar el domicilio que se usará a efectos de facturación.</p>
        <p class='mb-4'>Antes de efectuar el pago, el usuario deberá aceptar los terminos y condiciones de <b>NFORMAR</b>. Encaso de error por parte del usuario en la introducción de los datos de compra,dispondrá de mecanismos de corrección accesibles durante todo el proceso.</p>
        <p class='mb-4'>La verificación de los datos del proceso de compra será responsabilidad única del usuario. Una vez realizada la confirmación de compra por el cliente.La contratación podrá realizarse únicamente en lengua española.</p>
        <p class='mb-4'><b><u>Responsabilidades de NFORMAR.</u></b> Garantizamos la calidad de los productos ofertados a través de esta web. La disponibilidad de la tienda depende directamente del estado de los sistemas de telecomunicación empleados para su publicación, y en particular de la red Internet, por lo que <b>NFORMAR</b> no puede responsabilizarse de los inconvenientes que tengan su origen en causas que escapan a su control, entre las que figurarán también los problemas derivados del software de conexión, sistema informático, módem, fluido eléctrico, o redes de telecomunicaciones.</p>
        <p class='mb-4'><b><u>Responsabilidades del usuario – cliente.</u></b> El usuario se obliga a realizar un uso lícito de los productos y servicios ofertados a través de la página web, sin contravenir la legislación vigente, ni lesionar los derechos e intereses de terceras personas. Asimismo, garantiza la veracidad y exactitud de los datos facilitados al cumplimentar los formularios de registro y de contratación, evitando causar de perjuicios a <b>NFORMAR</b> derivados de la incorrección de los mismos.</p>
        <p class='mb-4'><b><u>Nulidad parcial.</u></b> Si alguna de las presentes condiciones es declarada no válida, ilegal o no aplicable por cualquier tribunal de la jurisdicción competente, dicha condición se tendrá por no puesta, no considerándose nulo o ineficaz la totalidad del contrato,continuando vigente el resto del mismo. Para el caso de que se produzca una laguna legal respecto de la interpretación de cualquier aspecto o condición del contrato, la interpretación deberá realizarse en concordancia con los demás términos y condiciones, y en consideración a la finalidad y naturaleza del mismo. La distribución o copia no autorizada de cualquier contenido conllevará las acciones legales pertinentes por nuestra parte.</p>
        <p class='mb-4'><b><u>Jurisdicción y ley aplicable.</u></b>  Las presentes condiciones están redactadas en español, y se encuentran sometidas a la legislación española vigente. Para cualquier tipo de controversia derivada dela utilización de los servicios ofrecidos o de los contenidos propios de esta web, las partes, por la aceptación de estas Condiciones, se someterán a los Juzgados y Tribunales del domicilio del comprador. De acuerdo con lo dispuesto en el artículo 14 del Reglamento (UE) 524/2013 se informa a los consumidores residentes en la Unión Europea de la existencia de una Plataforma de resolución de litigios en línea que se encuentra disponible en el siguiente <a href='https://ec.europa.eu/consumers/odr/main/index.cfm?event=main.home.chooseLanguage'><b>enlace.</b></a></p>
        <p class='mb-4'><b><u>Confianza online.</u></b>
            Nuestra entidad se encuentra adherida a Confianza Online (Asociación sin ánimo de lucro), inscrita en el Registro Nacional de Asociaciones Grupo 1, Sección 1, número nacional 594400, CIF G85804011, Calle la Palma 59, Bajo A., 28015 Madrid (España). Para más información: <a target='blank' href='https://www.confianzaonline.es/'><b>www.confianzaonline.es</b></a>
            Estas Condiciones Generales se rigen por la ley española. Así mismo, en cumplimiento de lo dispuesto en la Ley de Resolución Alternativa de Litigios, informamos a los consumidores que, como entidad adherida y en los términos del <a target='blank' href='https://www.confianzaonline.es/doc/codigo_etico_confianzaonline.pdf'><b>Código Ético</b></a>, los usuarios podrán acudir a Confianza Online para la resolución alternativa de eventuales controversias (https://www.confianzaonline.es/como-reclamar/formulario-de-reclamaciones/). Si éstas se refieren a transacciones electrónicas con consumidores, o sobre protección de datos cuando estén relacionadas con este ámbito, las reclamaciones serán resueltas por el Comité de Mediación de Confianza Online, acreditado para la resolución alternativa de litigios en materia de consumo. Si las reclamaciones versan sobre publicidad digital, o sobre protección de datos relacionada con este ámbito, serán sometidas al Jurado de la Publicidad de AUTOCONTROL.
            Además te recordamos que puedes acceder a la plataforma de resolución de litigios en línea de la Unión Europea siguiendo este enlace: <a target='blank' href='https://ec.europa.eu/consumers/odr/main/?event=main.home2.show'><b>https://ec.europa.eu/consumers/odr/main/?event=main.home2.show</b></a></p>
        "
    ></generic-block>
@endsection
